FROM golang:1.17 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o fizzbuzz .

FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/fizzbuzz /fizzbuzz
COPY --from=builder /app/templates /templates
EXPOSE 8080
CMD ["/fizzbuzz", "serve"]
